<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: Source: auth/controller.js</title>

    <script src="scripts/prettify/prettify.js"> </script>
    <script src="scripts/prettify/lang-css.js"> </script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link type="text/css" rel="stylesheet" href="styles/prettify-tomorrow.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">Source: auth/controller.js</h1>

    



    
    <section>
        <article>
            <pre class="prettyprint source linenums"><code>const helper = require("./helper");

/**
 * authController namespace.
 * @namespace authController
 */

 /**
 * @desc Handler method for the 'signup' endpoint. Calls the 'signUp' helper function to add user data
 * to the db data store
 * @memberof authController
 * @param {string} user username of the new user taken from request body
 * @param {string} email email of the new user taken from request body
 * @param {string} password password of the new user taken from request body
 * @returns {User} On success, returns a 200 and the correct user JSON object. On error, returns a 500
 */
export const signUp = (req, res) => {
  console.log("====================================");
  console.log(req.body);
  console.log("=================controller===================");
  const { user, email, password } = req.body;
  helper
    .signUp(user, email, password)
    .then(result => {
      res.status(200).json(result);

    })
    .catch(err => {
      res.status(500).json(err);
    });
};

 /**
 * @desc Handler method for the 'login' endpoint. Calls the 'login' helper function to add user data
 * to the db data store
 * @memberof authController
 * @param {string} email email of the new user taken from request body
 * @param {string} password password of the new user taken from request body
 * @returns {User} On success, returns a 200 and a User object. On error, returns a 
 *  404 not found or 500 depending on the error
 */
export const login = (req, res, next) => {
  const { email, password } = req.body;
  console.log("====================================");
  console.log(req.body);
  console.log("=================controller===================");
  helper
    .login(email, password)
    .then(result => {
      res.status(200).json(result);
    })
    .catch(err => {
      if (err === "NOT FOUND") {
        res.status(404).json(err);
      } else {
        res.status(500).json(err);
      }
    });
};
</code></pre>
        </article>
    </section>




</div>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Namespaces</h3><ul><li><a href="authController.html">authController</a></li><li><a href="authHelper.html">authHelper</a></li><li><a href="quoteController.html">quoteController</a></li><li><a href="quoteHelper.html">quoteHelper</a></li></ul>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a> on Sun Oct 20 2019 21:38:24 GMT-0700 (Pacific Daylight Time)
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
